#
# winLAME - a frontend for the LAME encoding engine
# Copyright (c) 2000-2023 Michael Fink
#
# AppVeyor build configuration file.
#
version: 2.23.0.{build}

image: Visual Studio 2022

platform: Win32

configuration: AppVeyor

cache:
  - C:\Users\appveyor\AppData\Local\vcpkg\archives -> appveyor.yml
  - C:\projects\winlame\vcpkg_installed -> appveyor.yml

before_build:
  - ps: source\Patch-BuildVersion.ps1 -version $env:appveyor_build_version
  - cmd: nuget restore
  - cmd: |
      cd "C:\Tools\vcpkg"
      git pull > nul
      call .\bootstrap-vcpkg.bat -disableMetrics

build:
  project: winlame.sln
  parallel: true
  verbosity: minimal

artifacts:
- path: bin\Release\win*.dll
- path: bin\Release\win*.exe
- path: bin\Release\pdb\win*.pdb
- path: bin\Release\*.msi
- path: bin\Release\*.zip
