#
# winLAME - a frontend for the LAME encoding engine
# Copyright (c) 2000-2022 Michael Fink
#
# AppVeyor build configuration file
#
version: 2.22.0.{build}

image: Visual Studio 2022

platform: Win32

configuration: AppVeyor

cache:
  - C:\Users\appveyor\AppData\Local\vcpkg\archives -> appveyor.yml

before_build:
  - ps: source\Patch-BuildVersion.ps1 -version $env:appveyor_build_version
  - cmd: nuget restore

build:
  project: winlame.sln
  parallel: true
  verbosity: minimal

artifacts:
- path: bin\Release\win*.dll
- path: bin\Release\win*.exe
- path: bin\Release\pdb\win*.pdb
- path: bin\Release\*.msi
- path: bin\Release\*.zip
